org: gerardiruri31utec
service: pedidos-universidad

provider:
  name: aws
  runtime: python3.13
  timeout: 30
  stage: dev
  httpApi:
    cors: true
  iam:
    role: arn:aws:iam::058264221898:role/LabRole

  environment:
    TABLA_PEDIDOS: ${self:service}-pedidos-${sls:stage}
    TABLA_COCINA: ${self:service}-cocina-${sls:stage}
    TABLA_DESPACHADOR: ${self:service}-despachador-${sls:stage}
    TABLA_DELIVERY: ${self:service}-delivery-${sls:stage}

plugins:
  # plugin de step functions lo puedes re-activar cuando definas la máquina de estados
  # - serverless-step-functions

functions:
  pagadoACocina:
    handler: estado_pedidos.pagado_a_cocina
    reservedConcurrency: 3 # <= máximo 3 pedidos en este paso
    events:
      - httpApi:
          path: /pedidos/{id_pedido}/pagado-a-cocina
          method: post
      - sqs: # <= NUEVO: trigger SQS
          arn:
            Fn::GetAtt: [YAPAGADOSQueue, Arn]
          batchSize: 1

  cocinaAEmpaquetamiento:
    handler: estado_pedidos.cocina_a_empaquetamiento
    reservedConcurrency: 3
    events:
      - httpApi:
          path: /pedidos/{id_pedido}/cocina-a-empaquetamiento
          method: post
      - sqs:
          arn:
            Fn::GetAtt: [PEDIDOSYACOCINADOSQueue, Arn]
          batchSize: 1

  empaquetamientoADelivery:
    handler: estado_pedidos.empaquetamiento_a_delivery
    reservedConcurrency: 3
    events:
      - httpApi:
          path: /pedidos/{id_pedido}/empaquetamiento-a-delivery
          method: post
      - sqs:
          arn:
            Fn::GetAtt: [PEDIDOSLISTOSPARARECOGERQueue, Arn]
          batchSize: 1

  deliveryAEntregado:
    handler: estado_pedidos.delivery_a_entregado
    events:
      - httpApi:
          path: /pedidos/{id_pedido}/delivery-a-entregado
          method: post

  confirmarPaso:
    handler: estado_pedidos.confirmar_paso
    events:
      - httpApi:
          path: /workflow/confirmar
          method: post

resources:
  Resources:
    PedidosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-pedidos-${sls:stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH # PK
          - AttributeName: id
            KeyType: RANGE # SK

    CocinaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-cocina-${sls:stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id_pedido
            AttributeType: S
        KeySchema:
          - AttributeName: id_pedido
            KeyType: HASH # PK

    DespachadorTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-despachador-${sls:stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id_pedido
            AttributeType: S
        KeySchema:
          - AttributeName: id_pedido
            KeyType: HASH # PK

    DeliveryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-delivery-${sls:stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id_pedido
            AttributeType: S
        KeySchema:
          - AttributeName: id_pedido
            KeyType: HASH # PK

    # =============================
    # COLAS SQS POR PASO
    # =============================

    YAPAGADOSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: YAPAGADOS.fifo
        FifoQueue: true
        ContentBasedDeduplication: true
        VisibilityTimeout: 60

    PEDIDOSYACOCINADOSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: PEDIDOSYACOCINADOS.fifo
        FifoQueue: true
        ContentBasedDeduplication: true
        VisibilityTimeout: 60

    PEDIDOSLISTOSPARARECOGERQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: PEDIDOSLISTOSPARARECOGER.fifo
        FifoQueue: true
        ContentBasedDeduplication: true
        VisibilityTimeout: 60

